name: "Lint"
on: ["push", "pull_request"]

jobs:
  ci:
	name: "Lint Go code"
	runs-on: ubuntu-latest
	steps:
	- uses: actions/checkout@v1
	  with:
      fetch-depth: 1
	- uses: WillAbides/setup-go-faster@v1.7.0
	  with:
      go-version: 1.24
	- run: "go test ./..."
	- run: "go vet ./..."
	- uses: dominikh/staticcheck-action@v1.4.0
	  with:
      version: "latest"
      install-go: false
